name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install dependencies
      run: npm install  # Adjust this command based on your project

    - name: Build
      run: npm run build  # Adjust this command based on your project (e.g., npm run build, npm run compile, etc.)

    - name: Deploy to GitHub Pages
      run: |
        git config --global user.name "${{ github.actor }}"
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"
        git checkout --orphan gh-pages
        git --work-tree ./dist add --all
        git --work-tree ./dist commit -m "Deploy to GitHub Pages"
        git push origin HEAD:gh-pages --force
      env:
        NODE_ENV: production
